### ISSUE TITLE
Logo Image Placement

### ISSUE THREAD

**Issue by ArsalaMehr** [SufiaChoudhry/task-may-14#1]
Remove img tag of logo from ul li and place it inside header in a separate div , after that use flex in header
https://github.com/SufiaChoudhry/task-may-14/blob/e2d22bdd12aa5bea3086047c243712568ce0385e/index.html#L20

**Comment by SufiaChoudhry** [comment]
#20 mainy thek kr liya hai .

**Comment by SufiaChoudhry** [comment]
# 1 solve kr liya hai
